version: '3.4'

services:
  mainwebapp:
    image: ${DOCKER_REGISTRY-}mainwebapp
    build:
      context: .
      dockerfile: WebApps/MainWebApp/Dockerfile
    #depends_on: 
    #  - db

          
  maindb:
    build:
        context: .
        dockerfile: WebApps/MainWebApp/Data/Dockerfile


